export const SET_USERINFO = 'SET_USERINFO'
export const SET_FAVORITE_DOCTORS = 'SET_FAVORITE_DOCTORS'
export const SET_CURRENT_DOCTOR = 'SET_CURRENT_DOCTOR'
export const SET_RESERVE_DOCTORS = 'SET_RESERVE_DOCTORS'
